In [6]:
import pandas as pd
import numpy as np

# Simulando dados bagunçados de verdade
dados_sujos = pd.DataFrame({
    'nome': ['João Silva', 'maria santos', 'PEDRO COSTA', 'Ana Oliveira', 'joão silva',
             'Maria Santos', '', 'Carlos Lima', 'ana oliveira', 'Pedro Costa'],
    'departamento': ['TI', 'vendas', 'TI', 'RH', 'ti', 'Vendas', 'Marketing', 'TI', 'rh', ''],
    'salario': ['5000', '3500', 'R$ 7000', '4200', '5000', '3500', '', '6000', '4200', '7000'],
    'idade': [25, 30, '', 28, 25, 30, 22, 35, 28, 45],
    'email': ['joao@empresa.com', 'maria@empresa.com', 'pedro@empresa.com', '',
              'joao@empresa.com', 'maria2@empresa.com', 'carlos@empresa.com',
              'carlos@empresa.com', 'ana@empresa.com', 'pedro@empresa.com']
})

print("DADOS ORIGINAIS (BAGUNÇADOS):")
print(dados_sujos)

DADOS ORIGINAIS (BAGUNÇADOS):
           nome departamento  salario idade               email
0    João Silva           TI     5000    25    joao@empresa.com
1  maria santos       vendas     3500    30   maria@empresa.com
2   PEDRO COSTA           TI  R$ 7000         pedro@empresa.com
3  Ana Oliveira           RH     4200    28
4    joão silva           ti     5000    25    joao@empresa.com
5  Maria Santos       Vendas     3500    30  maria2@empresa.com
6                  Marketing             22  carlos@empresa.com
7   Carlos Lima           TI     6000    35  carlos@empresa.com
8  ana oliveira           rh     4200    28     ana@empresa.com
9   Pedro Costa                  7000    45   pedro@empresa.com

In [7]:
dados_sujos.info()
print('-'*8)
dados_sujos.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nome          10 non-null     object
 1   departamento  10 non-null     object
 2   salario       10 non-null     object
 3   idade         10 non-null     object
 4   email         10 non-null     object
dtypes: object(5)
memory usage: 532.0+ bytes
--------

              nome departamento salario  idade             email
count           10           10      10     10                10
unique          10            8       7      7                 7
top     João Silva           TI    5000     25  joao@empresa.com
freq             1            3       2      2                 2

In [8]:
print("=== INFORMAÇÕES GERAIS ===")
dados_sujos.info()

print("\n=== VALORES ÚNICOS POR COLUNA ===")
for coluna in dados_sujos.columns:
    print(f"{coluna}: {dados_sujos[coluna].nunique()} valores únicos")

print("\n=== VERIFICANDO NULOS ===")
print(dados_sujos.isnull().sum())

print("\n=== PRIMEIRAS 5 LINHAS ===")
print(dados_sujos.head())

=== INFORMAÇÕES GERAIS ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nome          10 non-null     object
 1   departamento  10 non-null     object
 2   salario       10 non-null     object
 3   idade         10 non-null     object
 4   email         10 non-null     object
dtypes: object(5)
memory usage: 532.0+ bytes

=== VALORES ÚNICOS POR COLUNA ===
nome: 10 valores únicos
departamento: 8 valores únicos
salario: 7 valores únicos
idade: 7 valores únicos
email: 7 valores únicos

=== VERIFICANDO NULOS ===
nome            0
departamento    0
salario         0
idade           0
email           0
dtype: int64

=== PRIMEIRAS 5 LINHAS ===
           nome departamento  salario idade              email
0    João Silva           TI     5000    25   joao@empresa.com
1  maria santos       vendas     3500    30  maria@empresa.com
2   PEDRO COSTA           TI  R$ 7000        pedro@empresa.com
3  Ana Oliveira           RH     4200    28
4    joão silva           ti     5000    25   joao@empresa.com

In [9]:
# Vamos investigar os nomes únicos
print("NOMES 'ÚNICOS' SEGUNDO O PANDAS:")
print(dados_sujos['nome'].unique())

NOMES 'ÚNICOS' SEGUNDO O PANDAS:
['João Silva' 'maria santos' 'PEDRO COSTA' 'Ana Oliveira' 'joão silva'
 'Maria Santos' '' 'Carlos Lima' 'ana oliveira' 'Pedro Costa']

In [10]:
print("#NOMES TRATADOS")

dados_sujos['nome'] = dados_sujos['nome'].str.title()

#NOMES TRATADOS

In [11]:
print(dados_sujos)

           nome departamento  salario idade               email
0    João Silva           TI     5000    25    joao@empresa.com
1  Maria Santos       vendas     3500    30   maria@empresa.com
2   Pedro Costa           TI  R$ 7000         pedro@empresa.com
3  Ana Oliveira           RH     4200    28
4    João Silva           ti     5000    25    joao@empresa.com
5  Maria Santos       Vendas     3500    30  maria2@empresa.com
6                  Marketing             22  carlos@empresa.com
7   Carlos Lima           TI     6000    35  carlos@empresa.com
8  Ana Oliveira           rh     4200    28     ana@empresa.com
9   Pedro Costa                  7000    45   pedro@empresa.com

In [12]:

print("\n=== VALORES ÚNICOS POR COLUNA ===")
for coluna in dados_sujos.columns:
    print(f"{coluna}: {dados_sujos[coluna].nunique()} valores únicos")

=== VALORES ÚNICOS POR COLUNA ===
nome: 6 valores únicos
departamento: 8 valores únicos
salario: 7 valores únicos
idade: 7 valores únicos
email: 7 valores únicos

In [13]:
dados_sujos['departamento'] = dados_sujos['departamento'].str.upper()
print(dados_sujos)

           nome departamento  salario idade               email
0    João Silva           TI     5000    25    joao@empresa.com
1  Maria Santos       VENDAS     3500    30   maria@empresa.com
2   Pedro Costa           TI  R$ 7000         pedro@empresa.com
3  Ana Oliveira           RH     4200    28
4    João Silva           TI     5000    25    joao@empresa.com
5  Maria Santos       VENDAS     3500    30  maria2@empresa.com
6                  MARKETING             22  carlos@empresa.com
7   Carlos Lima           TI     6000    35  carlos@empresa.com
8  Ana Oliveira           RH     4200    28     ana@empresa.com
9   Pedro Costa                  7000    45   pedro@empresa.com

In [14]:

print("\n=== VALORES ÚNICOS POR COLUNA ===")
for coluna in dados_sujos.columns:
    print(f"{coluna}: {dados_sujos[coluna].nunique()} valores únicos")

=== VALORES ÚNICOS POR COLUNA ===
nome: 6 valores únicos
departamento: 5 valores únicos
salario: 7 valores únicos
idade: 7 valores únicos
email: 7 valores únicos

In [15]:
print("Salários")
print(dados_sujos['salario'])
print("Tipo da coluna:", dados_sujos['salario'].dtype)

print("\nApós Remoção: ")
dados_sujos['salario'].str.replace('R$ ', '')

Salários
0       5000
1       3500
2    R$ 7000
3       4200
4       5000
5       3500
6
7       6000
8       4200
9       7000
Name: salario, dtype: object
Tipo da coluna: object

Após Remoção:

0    5000
1    3500
2    7000
3    4200
4    5000
5    3500
6
7    6000
8    4200
9    7000
Name: salario, dtype: object

In [16]:
dados_sujos['salario'] = dados_sujos['salario'].str.replace('R$ ', '')
print(dados_sujos)

           nome departamento salario idade               email
0    João Silva           TI    5000    25    joao@empresa.com
1  Maria Santos       VENDAS    3500    30   maria@empresa.com
2   Pedro Costa           TI    7000         pedro@empresa.com
3  Ana Oliveira           RH    4200    28
4    João Silva           TI    5000    25    joao@empresa.com
5  Maria Santos       VENDAS    3500    30  maria2@empresa.com
6                  MARKETING            22  carlos@empresa.com
7   Carlos Lima           TI    6000    35  carlos@empresa.com
8  Ana Oliveira           RH    4200    28     ana@empresa.com
9   Pedro Costa                 7000    45   pedro@empresa.com

In [17]:
dados_sujos['salario'] = pd.to_numeric(dados_sujos['salario'], errors='coerce')

In [18]:
dados_sujos.info()
print('='*5)
print("\n=== VALORES ÚNICOS POR COLUNA ===")
for coluna in dados_sujos.columns:
    print(f"{coluna}: {dados_sujos[coluna].nunique()} valores únicos")
print('='*8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nome          10 non-null     object
 1   departamento  10 non-null     object
 2   salario       9 non-null      float64
 3   idade         10 non-null     object
 4   email         10 non-null     object
dtypes: float64(1), object(4)
memory usage: 532.0+ bytes
=====

=== VALORES ÚNICOS POR COLUNA ===
nome: 6 valores únicos
departamento: 5 valores únicos
salario: 5 valores únicos
idade: 7 valores únicos
email: 7 valores únicos
========

In [19]:
dados_sujos['departamentos'] = dados_sujos['departamento'].str.upper()
print(dados_sujos)

dados_sujos.describe()

           nome departamento  salario idade               email departamentos
0    João Silva           TI   5000.0    25    joao@empresa.com            TI
1  Maria Santos       VENDAS   3500.0    30   maria@empresa.com        VENDAS
2   Pedro Costa           TI   7000.0         pedro@empresa.com            TI
3  Ana Oliveira           RH   4200.0    28                                RH
4    João Silva           TI   5000.0    25    joao@empresa.com            TI
5  Maria Santos       VENDAS   3500.0    30  maria2@empresa.com        VENDAS
6                  MARKETING      NaN    22  carlos@empresa.com     MARKETING
7   Carlos Lima           TI   6000.0    35  carlos@empresa.com            TI
8  Ana Oliveira           RH   4200.0    28     ana@empresa.com            RH
9   Pedro Costa                7000.0    45   pedro@empresa.com

           salario
count     9.000000
mean   5044.444444
std    1358.410018
min    3500.000000
25%    4200.000000
50%    5000.000000
75%    6000.000000
max    7000.000000

In [20]:
print("\n=== VALORES ÚNICOS POR COLUNA ===")
for coluna in dados_sujos.columns:
    print(f"{coluna}: {dados_sujos[coluna].nunique()} valores únicos")

=== VALORES ÚNICOS POR COLUNA ===
nome: 6 valores únicos
departamento: 5 valores únicos
salario: 5 valores únicos
idade: 7 valores únicos
email: 7 valores únicos
departamentos: 5 valores únicos

In [21]:
print("=== DIAGNÓSTICO DE VALORES NULOS ===")
print(dados_sujos.isnull().sum())

print('='*8)

print("\n=== VISUALIZANDO AS LINHAS COM PROBLEMAS ===")
# Mostra linhas onde QUALQUER coluna tem NaN
linhas_com_nan = dados_sujos[dados_sujos.isnull().any(axis=1)]
print(linhas_com_nan)

=== DIAGNÓSTICO DE VALORES NULOS ===
nome             0
departamento     0
salario          1
idade            0
email            0
departamentos    0
dtype: int64
========

=== VISUALIZANDO AS LINHAS COM PROBLEMAS ===
  nome departamento  salario idade               email departamentos
6         MARKETING      NaN    22  carlos@empresa.com     MARKETING

In [22]:
  dados_sujos['departamentos'] = dados_sujos['departamentos'].str.upper()
print(dados_sujos)

           nome departamento  salario idade               email departamentos
0    João Silva           TI   5000.0    25    joao@empresa.com            TI
1  Maria Santos       VENDAS   3500.0    30   maria@empresa.com        VENDAS
2   Pedro Costa           TI   7000.0         pedro@empresa.com            TI
3  Ana Oliveira           RH   4200.0    28                                RH
4    João Silva           TI   5000.0    25    joao@empresa.com            TI
5  Maria Santos       VENDAS   3500.0    30  maria2@empresa.com        VENDAS
6                  MARKETING      NaN    22  carlos@empresa.com     MARKETING
7   Carlos Lima           TI   6000.0    35  carlos@empresa.com            TI
8  Ana Oliveira           RH   4200.0    28     ana@empresa.com            RH
9   Pedro Costa                7000.0    45   pedro@empresa.com

In [33]:
dados_limpos = dados_sujos.copy()

In [34]:
dados_limpos = dados_sujos.drop([2, 3, 4, 6]).reset_index(drop=True)
print(dados_limpos)

           nome departamento  salario idade               email departamentos
0    João Silva           TI   5000.0    25    joao@empresa.com            TI
1  Maria Santos       VENDAS   3500.0    30   maria@empresa.com        VENDAS
2  Maria Santos       VENDAS   3500.0    30  maria2@empresa.com        VENDAS
3   Carlos Lima           TI   6000.0    35  carlos@empresa.com            TI
4  Ana Oliveira           RH   4200.0    28     ana@empresa.com            RH
5   Pedro Costa                7000.0    45   pedro@empresa.com

In [40]:
dados_limpos.loc[5, 'departamento'] = 'TI'
print(dados_limpos)

           nome departamento  salario idade               email
0    João Silva           TI   5000.0    25    joao@empresa.com
1  Maria Santos       VENDAS   3500.0    30   maria@empresa.com
2  Maria Santos       VENDAS   3500.0    30  maria2@empresa.com
3   Carlos Lima           TI   6000.0    35  carlos@empresa.com
4  Ana Oliveira           RH   4200.0    28     ana@empresa.com
5   Pedro Costa           TI   7000.0    45   pedro@empresa.com